# logic/tool_registry.py
# ============================================================
# OBIX ConfigDoctor — canonical Tool Registry (Phase 3)
#
# Single source of truth for every public tool/page in the app.
# Generated once from the previously-hand-maintained tool list
# that lived only inside templates/partials/nav.html's Tool
# Launcher JS (TP_TOOLS). That copy has now been removed —
# nav.html reads this registry via a small Jinja-rendered JSON
# blob instead (see partials/nav.html), so there is exactly ONE
# place this data is maintained.
#
# `category` intentionally matches nav.html's existing taxonomy
# (TUNE / HW / ANALYZE / VIDEO / EXPLORE) rather than the newer
# landing-page grouping (TUNE/HARDWARE/SETUP/LEARN) used for the
# Command Center — nav.html's desktop mega-menu has several
# dropdown blocks keyed on these exact category strings, and
# renaming them is out of scope for this batch. The Command
# Center (Phase 2) maps these onto its own display groups instead
# of renaming the registry itself.
#
# Consumers:
#   - templates/partials/nav.html  (Tool Launcher search/panel)
#   - blueprints/meta.py           (sitemap.xml generation)
#   - landing.html command center  (Phase 2 — future batch)
#
# Each entry:
#   id                    stable slug, e.g. "app", "pid-advisor"
#   route                 the Flask URL path
#   label                 display name
#   description           short Thai description (shown in UI)
#   category              TUNE | HW | ANALYZE | VIDEO | EXPLORE
#   icon                  inline Lucide SVG markup
#   priority              sitemap priority (0.0-1.0)
#   changefreq            sitemap changefreq
#   status                stable | beta | experimental
#   input_type            what the user provides
#   output_type           what the tool produces
#   firmware_dependency   True if output includes Betaflight CLI
#                         syntax that can vary by firmware version
#   keywords              search terms for the Tool Launcher
# ============================================================

TOOL_REGISTRY = [
    {
        'id': 'app',
        'route': '/app',
        'label': 'Drone Analyzer',
        'description': 'PID · Filter · Flight time · Motor physics',
        'category': 'TUNE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 10 7 7" /><path d="m10 14-3 3" /><path d="m14 10 3-3" /><path d="m14 14 3 3" /><path d="M14.205 4.139a4 4 0 1 1 5.439 5.863" /><path d="M19.637 14a4 4 0 1 1-5.432 5.868" /><path d="M4.367 10a4 4 0 1 1 5.438-5.862" /><path d="M9.795 19.862a4 4 0 1 1-5.429-5.873" /><rect x="10" y="8" width="4" height="8" rx="1" /></svg>',
        'priority': 0.9,
        'changefreq': 'weekly',
        'status': 'stable',
        'input_type': 'form',
        'output_type': 'cli+report',
        'firmware_dependency': True,
        'keywords': ['analyzer', 'pid', 'filter', 'thrust', 'battery'],
    },
    {
        'id': 'pid_advisor',
        'route': '/pid-advisor',
        'label': 'PID Symptom Advisor',
        'description': 'บอกอาการ → รับคำแนะนำ PID/Filter + CLI',
        'category': 'TUNE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2" /></svg>',
        'priority': 0.9,
        'changefreq': 'weekly',
        'status': 'stable',
        'input_type': 'symptom_form',
        'output_type': 'cli+advice',
        'firmware_dependency': True,
        'keywords': ['pid', 'symptom', 'oscillation', 'cli'],
    },
    {
        'id': 'quick_tune',
        'route': '/quick-tune',
        'label': 'Quick Tune Pad',
        'description': 'เลือกอาการ → PID delta + CLI พร้อม copy',
        'category': 'TUNE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z" /></svg>',
        'priority': 0.9,
        'changefreq': 'weekly',
        'status': 'stable',
        'input_type': 'symptom_form',
        'output_type': 'cli_delta',
        'firmware_dependency': True,
        'keywords': ['quick tune', 'pid delta', 'cli'],
    },
    {
        'id': 'rpm_filter',
        'route': '/rpm-filter',
        'label': 'RPM Filter Calculator',
        'description': 'คำนวณ harmonic Hz + dyn_notch',
        'category': 'TUNE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m12 14 4-4" /><path d="M3.34 19a10 10 0 1 1 17.32 0" /></svg>',
        'priority': 0.8,
        'changefreq': 'weekly',
        'status': 'stable',
        'input_type': 'form',
        'output_type': 'cli',
        'firmware_dependency': True,
        'keywords': ['rpm filter', 'dyn_notch', 'harmonic'],
    },
    {
        'id': 'rates_visualizer',
        'route': '/rates-visualizer',
        'label': 'Rates Visualizer',
        'description': 'Real-time rate curve · per-axis',
        'category': 'TUNE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 7h6v6" /><path d="m22 7-8.5 8.5-5-5L2 17" /></svg>',
        'priority': 0.8,
        'changefreq': 'weekly',
        'status': 'stable',
        'input_type': 'form',
        'output_type': 'chart+cli',
        'firmware_dependency': True,
        'keywords': ['rates', 'expo', 'curve'],
    },
    {
        'id': 'bf_wizard',
        'route': '/bf-wizard',
        'label': 'BF Config Wizard',
        'description': '7 ขั้นตอน → CLI พร้อม paste',
        'category': 'TUNE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m21.64 3.64-1.28-1.28a1.21 1.21 0 0 0-1.72 0L2.36 18.64a1.21 1.21 0 0 0 0 1.72l1.28 1.28a1.2 1.2 0 0 0 1.72 0L21.64 5.36a1.2 1.2 0 0 0 0-1.72" /><path d="m14 7 3 3" /><path d="M5 6v4" /><path d="M19 14v4" /><path d="M10 2v2" /><path d="M7 8H3" /><path d="M21 16h-4" /><path d="M11 3H9" /></svg>',
        'priority': 0.9,
        'changefreq': 'weekly',
        'status': 'stable',
        'input_type': 'wizard',
        'output_type': 'cli',
        'firmware_dependency': True,
        'keywords': ['wizard', 'setup', 'betaflight', 'cli'],
    },
    {
        'id': 'motor_prop',
        'route': '/motor-prop',
        'label': 'Motor × Prop Recommender',
        'description': 'แนะนำ motor/prop ตาม KV + สเปค',
        'category': 'HW',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10.827 16.379a6.082 6.082 0 0 1-8.618-7.002l5.412 1.45a6.082 6.082 0 0 1 7.002-8.618l-1.45 5.412a6.082 6.082 0 0 1 8.618 7.002l-5.412-1.45a6.082 6.082 0 0 1-7.002 8.618l1.45-5.412Z" /><path d="M12 12v.01" /></svg>',
        'priority': 0.8,
        'changefreq': 'weekly',
        'status': 'stable',
        'input_type': 'form',
        'output_type': 'recommendation',
        'firmware_dependency': False,
        'keywords': ['motor', 'prop', 'kv'],
    },
    {
        'id': 'esc_checker',
        'route': '/esc-checker',
        'label': 'ESC Compatibility Checker',
        'description': 'ตรวจ ESC amps · protocol · KV limit',
        'category': 'HW',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 20v2" /><path d="M12 2v2" /><path d="M17 20v2" /><path d="M17 2v2" /><path d="M2 12h2" /><path d="M2 17h2" /><path d="M2 7h2" /><path d="M20 12h2" /><path d="M20 17h2" /><path d="M20 7h2" /><path d="M7 20v2" /><path d="M7 2v2" /><rect x="4" y="4" width="16" height="16" rx="2" /><rect x="8" y="8" width="8" height="8" rx="1" /></svg>',
        'priority': 0.8,
        'changefreq': 'weekly',
        'status': 'stable',
        'input_type': 'form',
        'output_type': 'compatibility_report',
        'firmware_dependency': False,
        'keywords': ['esc', 'amps', 'protocol'],
    },
    {
        'id': 'battery_health',
        'route': '/battery-health',
        'label': 'Battery Health Advisor',
        'description': 'IR · Sag · Health Score',
        'category': 'HW',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m11 7-3 5h4l-3 5" /><path d="M14.856 6H16a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.935" /><path d="M22 14v-4" /><path d="M5.14 18H4a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h2.936" /></svg>',
        'priority': 0.8,
        'changefreq': 'weekly',
        'status': 'stable',
        'input_type': 'form',
        'output_type': 'score',
        'firmware_dependency': False,
        'keywords': ['battery', 'ir', 'sag'],
    },
    {
        'id': 'motor_thermal',
        'route': '/motor-thermal',
        'label': 'Motor Thermal Estimator',
        'description': 'อุณหภูมิ winding · thermal margin',
        'category': 'HW',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 4v10.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0Z" /></svg>',
        'priority': 0.8,
        'changefreq': 'weekly',
        'status': 'stable',
        'input_type': 'form',
        'output_type': 'estimate',
        'firmware_dependency': False,
        'keywords': ['motor', 'thermal', 'temperature'],
    },
    {
        'id': 'loop_analyzer',
        'route': '/loop-analyzer',
        'label': 'Control Loop Analyzer',
        'description': 'Stick→Prop latency chain',
        'category': 'HW',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" /><path d="M21 3v5h-5" /><path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" /><path d="M8 16H3v5" /></svg>',
        'priority': 0.8,
        'changefreq': 'weekly',
        'status': 'beta',
        'input_type': 'form',
        'output_type': 'latency_report',
        'firmware_dependency': False,
        'keywords': ['loop', 'latency', 'stick'],
    },
    {
        'id': 'blackbox',
        'route': '/blackbox',
        'label': 'Blackbox CSV Analyzer',
        'description': 'วิเคราะห์ flight log · PID score A–D',
        'category': 'ANALYZE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 3v16a2 2 0 0 0 2 2h16" /><path d="M18 17V9" /><path d="M13 17V5" /><path d="M8 17v-3" /></svg>',
        'priority': 1.0,
        'changefreq': 'weekly',
        'status': 'stable',
        'input_type': 'csv_upload',
        'output_type': 'score+chart',
        'firmware_dependency': True,
        'keywords': ['blackbox', 'log', 'pid score'],
    },
    {
        'id': 'cli_surgeon',
        'route': '/cli_surgeon',
        'label': 'CLI Surgeon',
        'description': 'วิเคราะห์ diff all / dump CLI',
        'category': 'ANALYZE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 19h8" /><path d="m4 17 6-6-6-6" /></svg>',
        'priority': 0.9,
        'changefreq': 'weekly',
        'status': 'stable',
        'input_type': 'text_paste',
        'output_type': 'diff+advice',
        'firmware_dependency': True,
        'keywords': ['cli', 'dump', 'diff all'],
    },
    {
        'id': 'cli_comparator',
        'route': '/cli-comparator',
        'label': 'CLI Diff Comparator',
        'description': 'วาง 2 config → เห็นทุกค่าที่เปลี่ยน',
        'category': 'ANALYZE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v18" /><path d="m19 8 3 8a5 5 0 0 1-6 0zV7" /><path d="M3 7h1a17 17 0 0 0 8-2 17 17 0 0 0 8 2h1" /><path d="m5 8 3 8a5 5 0 0 1-6 0zV7" /><path d="M7 21h10" /></svg>',
        'priority': 0.8,
        'changefreq': 'weekly',
        'status': 'stable',
        'input_type': 'text_paste_x2',
        'output_type': 'diff_table',
        'firmware_dependency': True,
        'keywords': ['cli', 'compare', 'diff'],
    },
    {
        'id': 'osd',
        'route': '/osd',
        'label': 'OSD Designer',
        'description': 'ออกแบบ OSD layout + export CLI',
        'category': 'ANALYZE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="20" height="14" x="2" y="3" rx="2" /><line x1="8" x2="16" y1="21" y2="21" /><line x1="12" x2="12" y1="17" y2="21" /></svg>',
        'priority': 0.7,
        'changefreq': 'weekly',
        'status': 'stable',
        'input_type': 'designer',
        'output_type': 'cli+image',
        'firmware_dependency': True,
        'keywords': ['osd', 'layout', 'export'],
    },
    {
        'id': 'build_card',
        'route': '/build-card',
        'label': 'Build Card Generator',
        'description': 'สร้างรูปสเปคแชร์ Social',
        'category': 'ANALYZE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="20" height="14" x="2" y="5" rx="2" /><line x1="2" x2="22" y1="10" y2="10" /></svg>',
        'priority': 0.8,
        'changefreq': 'weekly',
        'status': 'beta',
        'input_type': 'form',
        'output_type': 'image_export',
        'firmware_dependency': False,
        'keywords': ['build card', 'spec', 'share'],
    },
    {
        'id': 'tuning_log',
        'route': '/tuning-log',
        'label': 'Tuning Log',
        'description': 'บันทึก session · เปรียบเทียบ PID',
        'category': 'ANALYZE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="8" height="4" x="8" y="2" rx="1" ry="1" /><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" /><path d="M12 11h4" /><path d="M12 16h4" /><path d="M8 11h.01" /><path d="M8 16h.01" /></svg>',
        'priority': 0.7,
        'changefreq': 'weekly',
        'status': 'stable',
        'input_type': 'form',
        'output_type': 'history',
        'firmware_dependency': False,
        'keywords': ['log', 'session', 'pid history'],
    },
    {
        'id': 'vtx',
        'route': '/vtx',
        'label': 'VTX Bands & Channels',
        'description': 'ตาราง Band/Channel + CLI generator',
        'category': 'VIDEO',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16.247 7.761a6 6 0 0 1 0 8.478" /><path d="M19.075 4.933a10 10 0 0 1 0 14.134" /><path d="M4.925 19.067a10 10 0 0 1 0-14.134" /><path d="M7.753 16.239a6 6 0 0 1 0-8.478" /><circle cx="12" cy="12" r="2" /></svg>',
        'priority': 0.6,
        'changefreq': 'monthly',
        'status': 'stable',
        'input_type': 'table_lookup',
        'output_type': 'cli',
        'firmware_dependency': True,
        'keywords': ['vtx', 'band', 'channel'],
    },
    {
        'id': 'vtx_range',
        'route': '/vtx-range',
        'label': 'VTX Range Calculator',
        'description': 'ประมาณระยะสัญญาณ + กราฟ',
        'category': 'VIDEO',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19.07 4.93A10 10 0 0 0 6.99 3.34" /><path d="M4 6h.01" /><path d="M2.29 9.62A10 10 0 1 0 21.31 8.35" /><path d="M16.24 7.76A6 6 0 1 0 8.23 16.67" /><path d="M12 18h.01" /><path d="M17.99 11.66A6 6 0 0 1 15.77 16.67" /><circle cx="12" cy="12" r="2" /><path d="m13.41 10.59 5.66-5.66" /></svg>',
        'priority': 0.6,
        'changefreq': 'monthly',
        'status': 'stable',
        'input_type': 'form',
        'output_type': 'chart',
        'firmware_dependency': False,
        'keywords': ['vtx', 'range', 'signal'],
    },
    {
        'id': 'vtx_smartaudio',
        'route': '/vtx-smartaudio',
        'label': 'VTX SmartAudio Guide',
        'description': 'SmartAudio / Tramp commands',
        'category': 'VIDEO',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 19v3" /><path d="M19 10v2a7 7 0 0 1-14 0v-2" /><rect x="9" y="2" width="6" height="13" rx="3" /></svg>',
        'priority': 0.6,
        'changefreq': 'monthly',
        'status': 'stable',
        'input_type': 'reference',
        'output_type': 'cli',
        'firmware_dependency': True,
        'keywords': ['smartaudio', 'tramp', 'vtx'],
    },
    {
        'id': 'fpv_trainer',
        'route': '/fpv-trainer',
        'label': 'FPV Training Simulator',
        'description': 'ฝึกบิน 3D · 4 โหมด · Gamepad',
        'category': 'EXPLORE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="6" x2="10" y1="11" y2="11" /><line x1="8" x2="8" y1="9" y2="13" /><line x1="15" x2="15.01" y1="12" y2="12" /><line x1="18" x2="18.01" y1="10" y2="10" /><path d="M17.32 5H6.68a4 4 0 0 0-3.978 3.59c-.006.052-.01.101-.017.152C2.604 9.416 2 14.456 2 16a3 3 0 0 0 3 3c1 0 1.5-.5 2-1l1.414-1.414A2 2 0 0 1 9.828 16h4.344a2 2 0 0 1 1.414.586L17 18c.5.5 1 1 2 1a3 3 0 0 0 3-3c0-1.545-.604-6.584-.685-7.258-.007-.05-.011-.1-.017-.151A4 4 0 0 0 17.32 5z" /></svg>',
        'priority': 0.9,
        'changefreq': 'weekly',
        'status': 'beta',
        'input_type': 'gamepad',
        'output_type': 'simulation',
        'firmware_dependency': False,
        'keywords': ['trainer', 'simulator', 'practice'],
    },
    {
        'id': 'flight_quiz',
        'route': '/flight-quiz',
        'label': 'Flight Style Quiz',
        'description': '5 คำถาม → rates + preset แนะนำ',
        'category': 'EXPLORE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10" /><circle cx="12" cy="12" r="6" /><circle cx="12" cy="12" r="2" /></svg>',
        'priority': 0.8,
        'changefreq': 'weekly',
        'status': 'stable',
        'input_type': 'quiz',
        'output_type': 'recommendation',
        'firmware_dependency': False,
        'keywords': ['quiz', 'rates', 'style'],
    },
    {
        'id': 'leaderboard',
        'route': '/leaderboard',
        'label': 'Config Leaderboard',
        'description': 'Vote · rank · copy config',
        'category': 'EXPLORE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 14.66v1.626a2 2 0 0 1-.976 1.696A5 5 0 0 0 7 21.978" /><path d="M14 14.66v1.626a2 2 0 0 0 .976 1.696A5 5 0 0 1 17 21.978" /><path d="M18 9h1.5a1 1 0 0 0 0-5H18" /><path d="M4 22h16" /><path d="M6 9a6 6 0 0 0 12 0V3a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1z" /><path d="M6 9H4.5a1 1 0 0 1 0-5H6" /></svg>',
        'priority': 0.8,
        'changefreq': 'weekly',
        'status': 'beta',
        'input_type': 'vote',
        'output_type': 'ranked_list',
        'firmware_dependency': False,
        'keywords': ['leaderboard', 'vote', 'config'],
    },
    {       
        'route': '/military-uas',
        'label': 'Military UAS Analyzer',
        'description': 'วิเคราะห์โดรนทหาร · physics engine',
        'category': 'EXPLORE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" /></svg>',
        'priority': 0.8,
        'changefreq': 'weekly',
        'status': 'experimental',
        'input_type': 'form',
        'output_type': 'report',
        'firmware_dependency': False,
        'keywords': ['military', 'uas', 'physics'],
    },
    {
        'id': 'fpv',
        'route': '/fpv',
        'label': 'FPV Knowledge Hub',
        'description': 'รวมบทความ & เครื่องมือ',
        'category': 'EXPLORE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 7v14" /><path d="M3 18a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h5a4 4 0 0 1 4 4 4 4 0 0 1 4-4h5a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-6a3 3 0 0 0-3 3 3 3 0 0 0-3-3z" /></svg>',
        'priority': 0.6,
        'changefreq': 'monthly',
        'status': 'stable',
        'input_type': 'browse',
        'output_type': 'article_index',
        'firmware_dependency': False,
        'keywords': ['knowledge hub', 'articles'],
    },
    {
        'id': 'fpv_gear',
        'route': '/fpv-gear',
        'label': 'FPV Gear Guide',
        'description': 'แนะนำอุปกรณ์ตาม class/style',
        'category': 'EXPLORE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="8" cy="21" r="1" /><circle cx="19" cy="21" r="1" /><path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" /></svg>',
        'priority': 0.7,
        'changefreq': 'weekly',
        'status': 'stable',
        'input_type': 'form',
        'output_type': 'recommendation',
        'firmware_dependency': False,
        'keywords': ['gear', 'hardware guide'],
    },
    {
        'id': 'downloads',
        'route': '/downloads',
        'label': 'Downloads',
        'description': 'DIFF & DUMP config files',
        'category': 'EXPLORE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 15V3" /><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><path d="m7 10 5 5 5-5" /></svg>',
        'priority': 0.7,
        'changefreq': 'weekly',
        'status': 'stable',
        'input_type': 'browse',
        'output_type': 'file_download',
        'firmware_dependency': False,
        'keywords': ['download', 'diff', 'dump'],
    },
    {
        'id': 'about',
        'route': '/about',
        'label': 'About',
        'description': 'ที่มา & วิธีใช้งาน',
        'category': 'EXPLORE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10" /><path d="M12 16v-4" /><path d="M12 8h.01" /></svg>',
        'priority': 0.5,
        'changefreq': 'monthly',
        'status': 'stable',
        'input_type': 'none',
        'output_type': 'article',
        'firmware_dependency': False,
        'keywords': ['about', 'how it works'],
    },
    {
        'id': 'team',
        'route': '/team',
        'label': 'Team',
        'description': 'ผู้พัฒนา & AI Partners',
        'category': 'EXPLORE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" /><path d="M16 3.128a4 4 0 0 1 0 7.744" /><path d="M22 21v-2a4 4 0 0 0-3-3.87" /><circle cx="9" cy="7" r="4" /></svg>',
        'priority': 0.7,
        'changefreq': 'monthly',
        'status': 'stable',
        'input_type': 'none',
        'output_type': 'article',
        'firmware_dependency': False,
        'keywords': ['team', 'developers'],
    },
    {
        'id': 'changelog',
        'route': '/changelog',
        'label': 'Changelog',
        'description': 'บันทึกการอัปเดต',
        'category': 'EXPLORE',
        'icon': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8" /><path d="M3 3v5h5" /><path d="M12 7v5l4 2" /></svg>',
        'priority': 0.5,
        'changefreq': 'weekly',
        'status': 'stable',
        'input_type': 'none',
        'output_type': 'article',
        'firmware_dependency': False,
        'keywords': ['changelog', 'updates'],
    },
]


def get_tools(category=None, status=None):
    """Return registry entries, optionally filtered by category/status."""
    tools = TOOL_REGISTRY
    if category:
        tools = [t for t in tools if t['category'] == category.upper()]
    if status:
        tools = [t for t in tools if t['status'] == status]
    return tools


def get_tool_by_route(route):
    """Look up a single registry entry by its route, or None."""
    for t in TOOL_REGISTRY:
        if t['route'] == route:
            return t
    return None


def get_categories():
    """Ordered list of distinct categories present in the registry."""
    seen = []
    for t in TOOL_REGISTRY:
        if t['category'] not in seen:
            seen.append(t['category'])
    return seen
